#theme: minima
remote_theme: jekyll/minima # to override Github Actions' default one
title: "Ondřej Frei's coding blog"
author:
  name: Ondřej Frei
  email: "frei.ondrej@pm.me"
minima:
  skin: auto
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ondřej-frei-210569278" }
